[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font]
size = 13.0

[font.offset]
x = 1   # space between characters
y = 1  # keep line spacing unchanged

[colors.primary]
background = "#1e1f2f"
foreground = "#ffffff"

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001f"
