#!/bin/bash

# Make sure brew is installed
if ! command -v brew &> /dev/null; then
    echo "Homebrew not found. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew is already installed."
fi

export CONFIG_HOME="$HOME/.config"
mkdir -p "$CONFIG_HOME"

ln -sf "$PWD/nvim" "$CONFIG_HOME/nvim"

ln -sf "$PWD/.bashrc" "$CONFIG_HOME/.bashrc"
ln -sf "$PWD/.tmux.conf" "$CONFIG_HOME/.tmux.conf"

packages=(
    fd
    ripgrep
    fzf
    npm
    lazygit
    kubectl
    argocd
    helm
    terraform
    docker
    azure-cli
    neovim
)

for package in "${packages[@]}"; do
    echo "Installing $package..."
    apt-get install -y "$package"
done

echo "All packages installed successfully."